### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by crazybored** [gitmylo/audio-webui#132]
I have an error while running run.bat on my Windows.
I just downloaded this and tried running it and got this error:
"No suitable Python runtime found
Pass --list (-0) to see all detected environments on your machine
or set environment variable PYLAUNCHER_ALLOW_INSTALL to use winget
or open the Microsoft Store to the requested version.
Press any key to continue . . ."
Before this, I believe it said something about downloading python from python.org, so I did that, and now I have this. How do I fix this?

**Comment by gitmylo** [comment]
Which python version did you download?

**Comment by crazybored** [comment]
> Which python version did you download?

I got 3.11.5 on python's website.

**Comment by gitmylo** [comment]
> > Which python version did you download?
> 
> I got 3.11.5 on python's website.

Python 3.11 is not currently supported, only 3.10, make sure you have that version installed, you don't need to uninstall python 3.11 though, it's managed still.

**Comment by crazybored** [comment]
> > > Which python version did you download?
> > 
> > 
> > I got 3.11.5 on python's website.
> 
> Python 3.11 is not currently supported, only 3.10, make sure you have that version installed, you don't need to uninstall python 3.11 though, it's managed still.

So I was able to get it working, then it told me to download a different pip, which I did, but now when I try to run it, this is displayed over and over again until I close it.

Checking installs and venv + autodebug checks
Python version:  3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
Webui version: 82dcef0e059661d496d8467be2303eed3510a657 - Fri Sep 8 20:09:30 2023 +0200
Found extensions:
activating venv

**Comment by gitmylo** [comment]
This usually happens when you're already in a venv, if you want to launch it while already in a venv, you can skip that part by adding `--skip-venv` to the launch flags.

If you're not already in a venv, and getting the repeated activations, i recommend manually activating a venv and then running with the `--skip-venv` flag, while technically you can use the flag without using a venv, in that case it will install the packages globally for python 3.10, which i do not recommend.

**Comment by crazybored** [comment]
I apologize, but I am new to this kind of stuff. What is a venv and where do I input that command you sent?

**Comment by gitmylo** [comment]
Run the `activate_only.bat`, and type `python main.py --skip-venv`
the activate_only.bat will open a cmd which has the venv (virtual environment) activated, so within this cmd, running `python` will use the python version from the venv (3.10)
Then running `python main.py --skip-venv` will launch the webui, skipping the check for a venv (since we already have it activated)

**Comment by gitmylo** [comment]
If you want to clone your voice for text to speech, you can use bark in the text to speech models, and as the voice select the clone option.

**Comment by crazybored** [comment]
Thank you. It is working now. I apologize for bothering you.
