### ISSUE TITLE
Looping venv. 

### ISSUE THREAD

**Issue by Innomen** [gitmylo/audio-webui#33]
Explored the issue with chatgpt and it gives me the following:
I asked it why the contents of venv.py would cause a loop.

> The problem with this script is in the activate_venv() function. When the virtual environment (venv) is not activated, it tries to activate it and then it calls itself by running the script again inside the venv. This leads to an infinite recursion, as the new script instance will again check if it's in a venv, and if not, it will try to activate it and call itself again, and so on.

> Here's the problem in more detail:
> 
> In the line:
> 
> python
> Copy code
> run_command([('call' if is_windows() else 'source', venv_activate_path), ('python', ' '.join([f'"{arg}"' for arg in sys.argv]))])
> The run_command function seems to be running a command which involves both activating the venv and then running the same Python script (since sys.argv contains the command-line arguments, which in this case would be the script itself).
> 
> This is followed by exit(), which would normally stop execution, but because you've launched another instance of the script inside the run_command function, this exit command doesn't stop the recursion from happening.
> 
> One way to solve this problem could be to refactor the script so that the script doesn't call itself. Instead of calling the script again after activating the venv, you could just run the code that needs the venv directly after activating it. This way, the venv will be activated only once, and there won't be any infinite recursion.
> 
> Please note that to do this, you might need to refactor your script to be able to run the code you want from within the script, rather than needing to start a new script instance. This would involve isolating the parts of the code that need the venv into a separate function, and then calling this function directly after the venv activation. This would avoid the recursion issue.

**Comment by gitmylo** [comment]
you didn't give enough context to chatgpt. this part of the script was written this way on purpose, to automatically activate the virtual environment. as you can't just swap interpreter mid-run. that's not possible.

the real reason you might be looping could be a few things, but it's probably this:

you're in a non-venv virtual environment (such as conda, pipenv, etc), which could not be detected (for whatever reason), but also not changed. (in which case the fix is usually to use the `--skip-venv` flag)

*but before you do that*, are you in a virtual environment? which operating system are you on? and which python version are you running with?

**Comment by Innomen** [comment]
Firstly, thank you for answering. Chatgpt? I thought this was an offline/local thing. Python 3.11.3. Windows 11.

**Comment by gitmylo** [comment]
I was referring to where you said you used ChatGPT to debug.
![image](https://github.com/gitmylo/audio-webui/assets/36931363/f107a88d-fb37-4a27-8290-17dfb1287f5e)

ChatGPT won't understand the code if you only show it the code from venv.py, because that's not enough context to understand the issue. The issue is not within the code, it's more of an issue with inconsistencies with some python versions.

Did it create a venv folder inside of your audio-webui directory? Also, do you have a version of python 3.10 installed? That's the only version known to be supported, as older versions don't support pipe characters for type annotations, and i believe there isn't a TTS package for 3.11 yet

**Comment by Innomen** [comment]
Hehe sorry my bad. Yea python version was 3.11, I updated because it told me to, guess that was unwise. My whole process for making crap work is clearing error messages and there was a message about old version.

Now at Python 3.10.6. There is a venv folder. It still loops, and every time I test it it spins off a billion background processes and I have to reboot to clear them.

**Comment by gitmylo** [comment]
try activating the venv, and then running with --skip-venv. this should work, just requires a bit of manual steps

**Comment by gitmylo** [comment]
reinstall? it doesn't have to reinstall if you just activate the venv and then run with `--skip-venv`, this will just skip the venv check.

i doubt an update of audio-webui caused the issue. as the venv activation code has been the same for the past month, if not longer.

it's not wrecked, it just isn't able to detect the venv, in which case it will try to activate it, and keep activating it because it keeps being unable to detect, `--skip-venv` changes this check to ignore this, and always continue.

if you delete the venv folder, you'll have to reinstall though, because all installed packages are stored in that folder.

**Comment by Innomen** [comment]
No no, not like an update of anything inside Audio, I mean when I updated python to 3.11. It ran fine before. I generated some audio and everything. Running audio in a command window would give like a log of it's actions, and in that log I'd see yellow text saying your python is old you should update, use this command in a window, so I did. That's what apparently broke everything. Besides, I don't know what you even mean by "activate the venv" I mean I follow the logic, run the thing myself so it doesn't loop trying to run it itself. And I'm sure that would work but that's a hack, I want it to work normally, like it did before. I want to understand how venv broke, and how to fix it, that will be useful in the future I'm sure.

**Comment by gitmylo** [comment]
if you run `py -3.10 -V` does it tell you a version of python 3.10 or does it give an error?

**Comment by gitmylo** [comment]
if it does work,
1. run `py -3.10`,
2. then in that interpreter, run `import sys`
3. then `getattr(sys, "base_prefix", None) or getattr(sys, "real_prefix", None) or sys.prefix`
4. write the output down somewhere
5. then activate your venv, and run `python`
6. then run `import sys` again
7. run `sys.prefix`

send me those 2 outputs, these 2 should not be the same when you're in a virtual environment.

**Comment by Innomen** [comment]
py -3.10 -V
'py' is not recognized as an internal or external command,
operable program or batch file.

python --version
Python 3.10.6

**Comment by gitmylo** [comment]
you don't have python installed with py launcher? i'd suggest you do, that might be causing this somehow.
install python from https://www.python.org/, this is the official version, do NOT use the windows store version, as it is known to cause issues. like with some other projects. and the windows store version does not install py, which is pretty bad, because py lets you launch a specific version, otherwise you need a different command for everything.

**Comment by gitmylo** [comment]
https://www.python.org/downloads/release/python-3108/

**Comment by gitmylo** [comment]
> Yea that's what I have. I don't use the windows store for anything. ![image](https://user-images.githubusercontent.com/134324/248295068-7ae4377d-e0f2-4242-8df0-2dc88746c7a2.png)
> 
> But https://www.python.org/downloads/release/python-31012/ Doesn't seem to have an installer.
> 
> I have a feeling py is only broken because I uninstalled 3.11. (Via add/remove programs like normal.)

well, when the run script doesn't detect the py command, it will use the python command and pray that it's the right version, if you installed python 3.11, it overwrote your path to use that version, then uninstalling it clears the key, so it won't be on your path anymore.

**Comment by Innomen** [comment]
py -3.10 -V
'py' is not recognized as an internal or external command,
operable program or batch file.

python --version
Python 3.10.8

Ahh I see.

I used [Windows installer (64-bit)](https://www.python.org/ftp/python/3.10.8/python-3.10.8-amd64.exe)

It did not offer any options such as PATH changes.

**Comment by gitmylo** [comment]
> py -3.10 -V 'py' is not recognized as an internal or external command, operable program or batch file.
> 
> python --version Python 3.10.8
> 
> Ahh I see.
> 
> I used [Windows installer (64-bit)](https://www.python.org/ftp/python/3.10.8/python-3.10.8-amd64.exe)
> 
> It did not offer any options such as PATH changes.

path changes are on by default, and that's fine, because you'll normally be using the py launcher, and the python command for the latest version.

**Comment by Innomen** [comment]
Ok. 
![image](https://github.com/gitmylo/audio-webui/assets/134324/8b4f8f52-3560-4907-a06a-04ad6d242402)
![image](https://github.com/gitmylo/audio-webui/assets/134324/0708634c-cb1e-49a5-9b6a-0d16038b10c7)

I reran the installer, selected modify, I watched it say it installed the py launcher and still...

'py' is not recognized as an internal or external command,
operable program or batch file.

I tried again as admin. 

Same problem. Why is it not installing the launcher?

**Comment by gitmylo** [comment]
did you reopen the cmd? the path variable gets saved locally to the cmd when it opens, so if it gets changed while it's still open it won't recognise it until you reopen cmd.

if that isn't it, add the py executable to your path manually

**Comment by Innomen** [comment]
How do I add it manually and why do I have to? it says it's installed. 
![image](https://github.com/gitmylo/audio-webui/assets/134324/01d4d374-c922-4e93-bf7f-17a75e641771)

**Comment by Innomen** [comment]
So many pythons to choose from. I'm becoming a deeply frustrated herpetologist.

**Comment by gitmylo** [comment]
![image](https://github.com/gitmylo/audio-webui/assets/36931363/b925231c-1ab7-442f-88d4-38c3ee2ff013)
![image](https://github.com/gitmylo/audio-webui/assets/36931363/7460ffee-033e-4267-a765-d825d57806ef)
![image](https://github.com/gitmylo/audio-webui/assets/36931363/b9a8f519-9367-4da1-9905-30c5095590ae)

although in my case py is installed in `C:/Windows` directly

**Comment by Innomen** [comment]
my path has 
C:\Users\Innomen\AppData\Local\Programs\Python\Python310\Scripts\
C:\Users\Innomen\AppData\Local\Programs\Python\Python310\

Where is py hiding?

naturally I can't just search for "py" I get all the pythons back.

**Comment by Innomen** [comment]
I don't have py.exe anywhere. Is that not what it's called?

**Comment by Innomen** [comment]
Wait I do have it in c: windows. Do I have to add windows itself to the path? Edit: JFC yes I do. Which is the dumbest shit in the world. py -3.10 -V
Python 3.10.8

Finally.

**Comment by gitmylo** [comment]
there must be something wrong somewhere, still. try following these steps again, and send me the output https://github.com/gitmylo/audio-webui/issues/33#issuecomment-1604360995

**Comment by Innomen** [comment]
Oh yea sorry I forgot why we went down the py rabbit hole. 

'C:\\Users\\Innomen\\AppData\\Local\\Programs\\Python\\Python310'

>>> python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined

How do I "activate your venv"?

**Comment by gitmylo** [comment]
you can activate the venv by runnin the `activate.bat` which is (on windows) inside of `venv\Scripts\activate.bat`

**Comment by Innomen** [comment]
Ok sorry for the delay. I've rerun the install with manual activate and skip venv, and now doing run. It's had to redownload some things. Once I can confirm I can get it running with manual and skip venv, I'll try again normally. I appreciate you taking the time to walk me through all this. I'm definitely learning things.

**Comment by gitmylo** [comment]
yeah, just remember to activate the venv every time you run, i also suggest `--skip-install` on future runs so it launches quicker
