### ISSUE TITLE
[FEATURE REQUEST] Collapse help using accordeon

### ISSUE THREAD

**Issue by pravdomil** [gitmylo/audio-webui#35]
<img width="590" alt="image" src="https://github.com/gitmylo/audio-webui/assets/2387356/218cd790-3276-4306-97b0-e9014b5b1c10">

**Comment by gitmylo** [comment]
i wish i could, but accordions don't work very well, maybe i can somehow do it with css.

**Comment by pravdomil** [comment]
why they dont work?

**Comment by pravdomil** [comment]
you can use `<details><summary>` then

**Comment by gitmylo** [comment]
you can't set visible on an accordion, sadly. but maybe i can set el-classes or whatever it's called

**Comment by gitmylo** [comment]
you cannot set elem-classes on textboxes though, so that won't work either

**Comment by pravdomil** [comment]
this looks clean
<img width="1175" alt="image" src="https://github.com/gitmylo/audio-webui/assets/2387356/e36fdfc4-a672-4fc1-a104-c26a931410aa">

put  under text area `Split your long form generations with newlines (enter), every line will be generated individually, but as a continuation of the last. Empty lines at the start and end will be skipped.`

and put
```Clear spoken, no noise, no music. Ends after a short pause for best results.
When cloning a voice:
- The speaker will be saved in the data/bark_custom_speakers directory.
- The “file” output contains a different speaker. This is for saving speakers created through random generation. Or continued cloning.
```

under file upload

**Comment by gitmylo** [comment]
i got the accordion working, maybe it was fixed in a gradio update?

**Comment by pravdomil** [comment]
and what is this?

https://github.com/gitmylo/audio-webui/commit/2396a45aa8f2c123171edb3f0170a73c6c588a04

<img width="1261" alt="image" src="https://github.com/gitmylo/audio-webui/assets/2387356/33402c1c-ee64-4a8d-9df4-c0cc11d9b9df">

**Comment by gitmylo** [comment]
> and what is this?
> 
> [2396a45](https://github.com/gitmylo/audio-webui/commit/2396a45aa8f2c123171edb3f0170a73c6c588a04)
> <img alt="image" width="1261" src="https://user-images.githubusercontent.com/2387356/248395400-33402c1c-ee64-4a8d-9df4-c0cc11d9b9df.png">

the accordion element has to be sent through to the ui manager so it can be correctly hidden and shown when it becomes relevant or irrelevant.

![image](https://github.com/gitmylo/audio-webui/assets/36931363/493fe050-e472-4142-ba0a-9ee68c3f4db3)

these are all workarounds, because gradio does not support replacing of elements, so you have to hide them somehow, and i'm definitely not going to write down each individual element, so i made that code to manage it.

![image](https://github.com/gitmylo/audio-webui/assets/36931363/87d255d5-6044-4678-aee4-ec9bd2c3f557)

the reason it is not included on the other side, in the inputs, is because the versions after 5aa6e6972b5ad32e23a7871efc6095b1de821ce0 skip any elements which aren't inputs.

[Bonus] Here's some screenshots from when i had just implemented the hiding system:

![image](https://github.com/gitmylo/audio-webui/assets/36931363/6594b54d-5d16-4edd-af85-a323c2e44342)
![image](https://github.com/gitmylo/audio-webui/assets/36931363/db01fe01-1344-446d-bbae-daa7257f55c9)

**Comment by pravdomil** [comment]
ok, now it looks good

**Comment by pravdomil** [comment]
this can be a better design

![image](https://github.com/gitmylo/audio-webui/assets/2387356/9352172e-b00f-4238-8656-56ddcd902e49)

**Comment by gitmylo** [comment]
sounds more relevant to #39

**Comment by gitmylo** [comment]
also, planning to add a smart split option, but i'll add the hint for now

**Comment by pravdomil** [comment]
I made a new issue to be clear https://github.com/gitmylo/audio-webui/issues/40
