### ISSUE TITLE
[BUG REPORT] ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by peepeepeepoopoopoo** [gitmylo/audio-webui#49]
**at the end it tells me that I have visual C++ build tools installed, but I already had it**

**Error:**

C:\Users\USUARIO\Desktop\nylo\audio-webui\venv\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USUARIO\Desktop\nylo\audio-webui\main.py", line 24, in <module>
    from webui.webui import launch_webui
  File "C:\Users\USUARIO\Desktop\nylo\audio-webui\webui\webui.py", line 1, in <module>
    from webui.ui.ui import create_ui
  File "C:\Users\USUARIO\Desktop\nylo\audio-webui\webui\ui\ui.py", line 2, in <module>
    from .tabs import *
  File "C:\Users\USUARIO\Desktop\nylo\audio-webui\webui\ui\tabs\__init__.py", line 7, in <module>
    from .training_tab import training_tab
  File "C:\Users\USUARIO\Desktop\nylo\audio-webui\webui\ui\tabs\training_tab.py", line 2, in <module>
    from webui.ui.tabs.training.rvc import train_rvc
  File "C:\Users\USUARIO\Desktop\nylo\audio-webui\webui\ui\tabs\training\rvc.py", line 2, in <module>
    import webui.ui.tabs.training.training.rvc_workspace as rvc_ws
  File "C:\Users\USUARIO\Desktop\nylo\audio-webui\webui\ui\tabs\training\training\rvc_workspace.py", line 33, in <module>
    from webui.modules.implementations.rvc.custom_pitch_extraction import pitch_extract as pe
  File "C:\Users\USUARIO\Desktop\nylo\audio-webui\webui\modules\implementations\rvc\custom_pitch_extraction.py", line 6, in <module>
    import pyworld
  File "C:\Users\USUARIO\Desktop\nylo\audio-webui\venv\lib\site-packages\pyworld\__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld\pyworld.pyx", line 6, in init pyworld.pyworld
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
numpy.core.multiarray failed to import
Your install might have failed to install one of the requirements, are you missing a package?
Depending on the error message that was given during install, you might need to install visual C++ build tools.
Or read common issues at https://github.com/gitmylo/audio-webui/wiki/common-issues

**Comment by gitmylo** [comment]
It seems you have an outdated numpy version from that error.

The error at the end is just suggesting a common fix, as visual C++ build tools are usually missing, i'll see if i can personalize the message more depending on the error that occurred.

back to the error,
1. run `activate_only.bat` if you're on windows `activate_only.sh` if you're on linux or macos.
2. run `pip freeze`
3. look for `numpy`
4. it should say something like `numpy==` and then some numbers. which numbers does it say?

**Comment by gitmylo** [comment]
Well, i added a numpy minimum version requirement. If you update and run again, it should not crash anymore.

**Comment by natlamir** [comment]
I had the same error yesterday, I am trying again today, and it was now giving me a different error.  This is the error when running run.bat:

Installed audiocraft!
Done installing/checking installs.
Preparing
C:\ai\audio-webui\venv\lib\site-packages\torchaudio\compliance\kaldi.py:22: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  EPSILON = torch.tensor(torch.finfo(torch.float).eps)
2023-06-29 10:55:50 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2023-06-29 10:55:50 | WARNING | xformers | A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2023-06-29 10:55:50 | WARNING | xformers | Triton is not available, some optimizations will not be enabled.
This is just a warning: No module named 'triton'
Install finished, pywintypes missing, relaunching script.
Checking installs and venv + autodebug checks
Python version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Installed numpy!

    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    █░▄▄▀██░██░█▄▄░▄▄██░▄▄▄░██░▄▄▀██░▄▄▄██░▄▄▀██░██░██░▄▄░██
    █░▀▀░██░██░███░████░███░██░██░██░▄▄▄██░▄▄▀██░██░██░█▀▀██
    █░██░██▄▀▀▄███░████░▀▀▀░██░▀▀░██░▀▀▀██░▀▀░██▄▀▀▄██░▀▀▄██
    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Install failed!
STDOUT:
Requirement already satisfied: numpy in c:\ai\audio-webui\venv\lib\site-packages (1.22.0)
Collecting numpy
  Using cached numpy-1.25.0-cp310-cp310-win_amd64.whl (15.0 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.0
    Uninstalling numpy-1.22.0:
      Successfully uninstalled numpy-1.22.0

STDERR:
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\ai\\audio-webui\\venv\\Lib\\site-packages\\~umpy\\.libs\\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll'
Check the permissions.

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Please read the error above carefully.
If you are unsure, please create an issue at https://github.com/gitmylo/audio-webui/issues.
When creating an issue, please include your full autodebug message.
Exit code: 1
---

Should the script be run as admin? I tried giving Authenticated Users the Full Control permissions for that dll and trying run.bat again, and it gave this error:

Preparing
Traceback (most recent call last):
  File "C:\ai\audio-webui\main.py", line 18, in <module>
    from webui.modules.implementations.tts_monkeypatching import patch as patch1
  File "C:\ai\audio-webui\webui\modules\implementations\__init__.py", line 1, in <module>
    import webui.modules.implementations.ttsmodels as tts
  File "C:\ai\audio-webui\webui\modules\implementations\ttsmodels.py", line 11, in <module>
    from TTS.api import TTS
  File "C:\ai\audio-webui\venv\lib\site-packages\TTS\api.py", line 13, in <module>
    from TTS.utils.audio.numpy_transforms import save_wav
  File "C:\ai\audio-webui\venv\lib\site-packages\TTS\utils\audio\__init__.py", line 1, in <module>
    from TTS.utils.audio.processor import AudioProcessor
  File "C:\ai\audio-webui\venv\lib\site-packages\TTS\utils\audio\processor.py", line 10, in <module>
    from TTS.utils.audio.numpy_transforms import compute_f0
  File "C:\ai\audio-webui\venv\lib\site-packages\TTS\utils\audio\numpy_transforms.py", line 7, in <module>
    from librosa import magphase, pyin
  File "C:\ai\audio-webui\venv\lib\site-packages\lazy_loader\__init__.py", line 77, in __getattr__
    attr = getattr(submod, name)
  File "C:\ai\audio-webui\venv\lib\site-packages\lazy_loader\__init__.py", line 76, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ai\audio-webui\venv\lib\site-packages\librosa\core\spectrum.py", line 12, in <module>
    from numba import jit
  File "C:\ai\audio-webui\venv\lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "C:\ai\audio-webui\venv\lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")
ImportError: Numba needs NumPy 1.24 or less
Numba needs NumPy 1.24 or less
Your install might have failed to install one of the requirements, are you missing a package?
You can read common issues at https://github.com/gitmylo/audio-webui/wiki/common-issues
---

I ran activate_only.bat, pip freeze. It says numpy==1.25.0
I ran pip install --upgrade numpy==1.23.5, which gives this error:

(venv) C:\ai\audio-webui>pip install --upgrade numpy==1.23.5
Collecting numpy==1.23.5
  Using cached numpy-1.23.5-cp310-cp310-win_amd64.whl (14.6 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.0
    Uninstalling numpy-1.25.0:
      Successfully uninstalled numpy-1.25.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tts 0.15.0 requires numpy==1.22.0; python_version <= "3.10", but you have numpy 1.23.5 which is incompatible.
fairseq 0.12.2 requires hydra-core<1.1,>=1.0.7, but you have hydra-core 1.3.2 which is incompatible.
fairseq 0.12.2 requires omegaconf<2.1, but you have omegaconf 2.3.0 which is incompatible.
Successfully installed numpy-1.23.5

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
---

However, now when I run run.bat, the application runs successfully after doing the above mentioned things.
Thanks.

**Comment by gitmylo** [comment]
i had updated it twice today, one update made it install a too new numpy version, but it's been changed to use the specific version that i use.

**Comment by nekogecko2** [comment]
>STDERR:
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\ai\audio-webui\venv\Lib\site-packages\~umpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll'
Check the permissions.

When I reinstalled this program in a new folder, I had all these same things happen to me too. 

Running activate.bat -> pip install --upgrade numpy==1.23.5 -> run.bat like you said fixed it

**Comment by gitmylo** [comment]
> > STDERR:
> > ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\ai\audio-webui\venv\Lib\site-packages~umpy.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll'
> > Check the permissions.
> 
> When I reinstalled this program in a new folder, I had all these same things happen to me too.
> 
> Running activate.bat -> pip install --upgrade numpy==1.23.5 -> run.bat like you said fixed it

current version doesn't require the --upgrade numpy anymore. as it's included in the auto installer. it will make sure you're on the right version.

**Comment by zba** [comment]
still have this error with latest code,  pip install --upgrade numpy==1.23.5 helped
