### ISSUE TITLE
Failed to install audiolm. Check AutoDebug output.

### ISSUE THREAD

**Issue by sanane-ulan** [gitmylo/audio-webui#68]
Hi,

I am trying to install using ./install.sh --skip-venv , but I am getting this error:

Failed to install audiolm. Check AutoDebug output.
Traceback (most recent call last):
  File "/mnt/SD_Partiton/TTS/audio-webui/install.py", line 15, in <module>
    ensure_installed()
  File "/mnt/SD_Partiton/TTS/audio-webui/install.py", line 11, in ensure_installed
    install_requirements()
  File "/mnt/SD_Partiton/TTS/audio-webui/setup_tools/magicinstaller/magicinstaller.py", line 4, in install_requirements
    requirement.install_or_upgrade_if_needed()
  File "/mnt/SD_Partiton/TTS/audio-webui/setup_tools/magicinstaller/requirement.py", line 30, in install_or_upgrade_if_needed
    self.post_install(self.install())
  File "/mnt/SD_Partiton/TTS/audio-webui/setup_tools/magicinstaller/requirement.py", line 36, in post_install
    raise InstallFailException(exit_code, stdout, stderr)
autodebug.autodebug.InstallFailException: Install failed!

=========================================================================

Then I try to install audiolm manually:

$ pip install audiolm-pytorch

and getting this error:
fairseq/clib/libbleu/module.cpp:9:10: fatal error: Python.h: No such file or directory
          9 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

Python version: 3.10.12
OS: Fedora Linux 37 (KDE Plasma) x86_64
GPU: NVIDIA GeForce GTX 960M (4GB)
Memory: 16GB

Can someone help me pls?

**Comment by gitmylo** [comment]
Since python 3.10 cannot be installed automatically through apt anymore, i'm assuming you built from source.

I personally use python 3.10.8, built from source. But it seems like you're missing a package and it's not really a version difference.

Here's a guide on manually building from source if you didn't know how to. https://ubuntuhandbook.org/index.php/2021/10/compile-install-python-3-10-ubuntu/

Just make sure you wget https://www.python.org/ftp/python/3.10.8/Python-3.10.8.tar.xz instead of python 3.11 like in the tutorial, the rest is the same.

**Comment by sanane-ulan** [comment]
Thanks, I am not using ubuntu, as I wrote I am on Fedora 37. I installed Python 3.10 through package manager DNF.

I will try to install python 3.8 and then try again to install with install.sh.

Is there anyway may I try to install manually if install.sh would not work?

Like copying git and installing install_requirements.txt 1 by 1?

Sorry if I bother you, I am just not good at coding

**Comment by gitmylo** [comment]
> Thanks, I am not using ubuntu, as I wrote I am on Fedora 37. I installed Python 3.10 through package manager DNF.
> 
> I will try to install python 3.8 and then try again to install with install.sh.
> 
> Is there anyway may I try to install manually if install.sh would not work?

You can launch with `--skip-install` and optionally `--skip-venv` if you want to manually use a venv.
> 
> Like copying git and installing install_requirements.txt 1 by 1?

Install_requirements.txt is a bit outdated compared to the automatic installer, and i doubt you'll have more luck with it too. As the error you got, is related to something missing in your python install.
> 
> Sorry if I bother you, I am just not good at coding

Another fix you could try is `sudo dnf install python3-devel`/`sudo dnf install python3.10-devel`, since you're on fedora, maybe the packages for 3.10 are still up?

**Comment by gitmylo** [comment]
Great!
