### ISSUE TITLE
[QUESTION] Where is the "Predict Epochs" button?

### ISSUE THREAD

**Issue by deklesen** [gitmylo/audio-webui#75]
In RVC training, the how-to tab talks about a 'Predict Epochs' button:

[                            * You can click the "Predict epochs" button to set your training epochs to the recommended amount based on how much data you have.
                            * ](https://github.com/gitmylo/audio-webui/blob/01c18abfc98a7dd2bac1a5837332507b057c5161/webui/ui/tabs/training/rvc.py#L87)

But, in the webui I don't see such a button. Where is it?

If that functionality is gone, maybe can we have a rule of thumb on how many epochs to train for per x minutes of input data?

Thanks!

**Comment by gitmylo** [comment]
It was removed because it wasn't as good as i had hoped. And it's better to just put in your own numbers. I'll remove it from the help.

I recommend if you have 10 minutes of audio, train for 50 epochs at least.
If you have 30 minutes of audio, training for 10 epochs will usually be enough.

If you notice it hasn't trained enough, continue training from that checkpoint by refreshing the model list, selecting the highest number, and continuing training.

**Comment by G-force78** [comment]
> It was removed because it wasn't as good as i had hoped. And it's better to just put in your own numbers. I'll remove it from the help.
> 
> I recommend if you have 10 minutes of audio, train for 50 epochs at least. If you have 30 minutes of audio, training for 10 epochs will usually be enough.
> 
> If you notice it hasn't trained enough, continue training from that checkpoint by refreshing the model list, selecting the highest number, and continuing training.

How do you use the new model in txt2speech?

**Comment by gitmylo** [comment]
> How do you use the new model in txt2speech?

If you're talking about RVC, which this issue is about, you have to first generate audio with text to speech, then use that audio as the input for RVC for voice conversion (voice changer).
