### ISSUE TITLE
[FEATURE REQUEST] AudioGen model has been released.

### ISSUE THREAD

**Issue by ohmygoobness** [gitmylo/audio-webui#97]
**Is your feature request related to a problem? Please describe.**
Facebook just released their AudioGen - Medium - 1.5B https://huggingface.co/facebook/audiogen-medium

**Describe the solution you'd like**
Addition of the model to the webui.

**Comment by gitmylo** [comment]
support has been added

**Comment by gitmylo** [comment]
I don't think you need bleeding edge to run it, i ran it on the main branch. But reinstalling audiocraft might be needed since i cannot normally check the version unless i lock it to a specific version, since comparisons only work for pypi packages, and with git packages you can only check if the version is equal to a certain version.

**Comment by nekogecko2** [comment]
> @gitmylo i had to install git+https://git@github.com/facebookresearch/audiocraft#egg=audiocraft 

Thanks that worked. I had a error after updating to latest version
