### ISSUE TITLE
[BUG REPORT] Only Odd numbers work in filter radius on RVC

### ISSUE THREAD

**Issue by nekogecko2** [gitmylo/audio-webui#99]
Might be related to this issue too: https://github.com/gitmylo/audio-webui/issues/90

Filter radius set to 0,1,3,5,7 works 

Filter radius set to 2,4,6 get the 
```
"ValueError: Each element of kernel_size should be odd."
"AttributeError: 'NoneType' object has no attribute 'dtype'"
```
errors

**Comment by gitmylo** [comment]
that's just how filter radius works

**Comment by gitmylo** [comment]
If you have a filter radius of 3 you want to get the number between 1 and 3, the number in the middle is 2, which is an integer (whole number), which can be indexed.
if you have a filter radius of 4 you want to get the number between 1 and 4, which is impossible, there is no number exactly between 1 and 4. so it can't work.

**Comment by GsHeri** [comment]
so then why are there options to choose 2, 4, 6 in the first place?

also: i did NOT work with 5 for me. i spent quite some time now finding out (or rather.. asking GPT :D ) that it was indeed related to the filter radius. 
it only works for 3, 
not 4, not 5, not 7

i kind of accept, that it "only works for odd numbers". but then it should work for 5 and 7. so this is (obviously) a bug.
also please remove settings that can, by design, never work (?)
(and maybe the error message should state that this is connected to filter radius)

**Comment by gitmylo** [comment]
i don't think i have enough control over the slider component to block even numbers, only odd ones, not even sure about that.
i could also take the value and do $floor(n)*2+1$ in which case it would be an odd number, although it wouldn't match other implementations which use the same slider.

**Comment by GsHeri** [comment]
well, if you have ANY control over the slider code, you could do min="1" step="2". that should do exactly this.

but as long as the other bug isn't fixed, you can just remove the slider altogether, since every other value except 3 doesn't work :D
